MAX_LEVEL = 90

DMG_TYPE_SCYTHE = 0
DMG_TYPE_MELEE = 1
DMG_TYPE_PIERCE = 2
DMG_TYPE_MAGIC = 3

SLOT_WEAPON = 0
SLOT_WEAPON_SPECIAL = 1
SLOT_HEAD = 2
SLOT_BACK = 3
SLOT_NECK = 4
SLOT_WAIST = 5
SLOT_FINGER = 6
SLOT_TRINKET = 7
SLOT_WRIST = 8
SLOT_PET = 9
SLOTS = (SLOT_WEAPON, SLOT_WEAPON_SPECIAL, SLOT_HEAD, SLOT_BACK, SLOT_NECK, SLOT_WAIST, SLOT_FINGER, SLOT_TRINKET, SLOT_WRIST, SLOT_PET)

SKILL_RETURN_CODE_DOUBLE_TURN = 2

ATTACK_CODE_SUCCESS = 3
ATTACK_CODE_UNSUCCESSFUL = 4

PER_ELEM_RESIST_CAP = 80
CRIT_CAP = 100

HP_POTION_SCALING_VALUE = 0.3
MP_POTION_SCALING_VALUE = 0.1

HP_POTION_MAX_LEVEL = 40
MP_POTION_MAX_LEVEL = 40

KEYBOARD_CONTROLS = ("N", "Z", "X", "1", "2", "3", "4", "5", " ", "6", "7", "8", "9", "0", "C", "V", "B", "M")

PLAYER_STUNNED_STR = "Stunned"
ENEMY_STUNNED_STR = "Stunned"
PLAYER_STUN_CHANCE = 0.34

DEFAULT_ON_HIT_SPECIAL = lambda match, entity, damage: damage
DEFAULT_ON_ATTACK_SPECIAL = lambda: None
RETURN_CODE_USED_ON_ATTACK_SPECIAL = 5

HP_MP_METER_LENGTH = 200  # The length of the HP and MP meters
