MAX_LEVEL = 90

DMG_TYPE_SCYTHE = 0
DMG_TYPE_MELEE = 1
DMG_TYPE_PIERCE = 2
DMG_TYPE_MAGIC = 3
DMG_TYPES = (DMG_TYPE_SCYTHE, DMG_TYPE_MELEE, DMG_TYPE_PIERCE, DMG_TYPE_MAGIC)
DMG_TYPE_NAMES = {DMG_TYPE_SCYTHE: "Scythe", DMG_TYPE_MELEE: "Melee", DMG_TYPE_PIERCE: "Pierce", DMG_TYPE_MAGIC: "Magic"}

SLOT_WEAPON = "weapon"
SLOT_WEAPON_SPECIAL = "weapon_special"
SLOT_HEAD = "head"
SLOT_BACK = "back"
SLOT_NECK = "neck"
SLOT_WAIST = "waist"
SLOT_FINGER = "finger"
SLOT_TRINKET = "trinket"
SLOT_WRIST = "wrist"
SLOT_PET = "pet"
SLOTS = (SLOT_WEAPON, SLOT_WEAPON_SPECIAL, SLOT_HEAD, SLOT_BACK, SLOT_NECK, SLOT_WAIST, SLOT_FINGER, SLOT_TRINKET, SLOT_WRIST, SLOT_PET)
INVENTORY_SLOTS = (SLOT_WEAPON, SLOT_WEAPON_SPECIAL, SLOT_HEAD, SLOT_BACK, SLOT_NECK, SLOT_WAIST, SLOT_FINGER, SLOT_WRIST)

SKILL_RETURN_CODE_DOUBLE_TURN = 2

ATTACK_CODE_SUCCESS = 3
ATTACK_CODE_UNSUCCESSFUL = 4

PER_ELEM_RESIST_CAP = 80
CRIT_CAP = 100

HP_POTION_SCALING_VALUE = 0.3
MP_POTION_SCALING_VALUE = 0.1

HP_POTION_MAX_LEVEL = 40
MP_POTION_MAX_LEVEL = 40

KEYBOARD_CONTROLS = ("N", "Z", "X", "1", "2", "3", "4", "5", " ", "6", "7", "8", "9", "0", "C", "V", "B", "M")

PLAYER_STUNNED_STR = "Stunned"
ENEMY_STUNNED_STR = "Stunned"
PLAYER_STUN_CHANCE = 0.34

HP_MP_METER_LENGTH = 200  # The length of the HP and MP meters

MANA_ELEMENT = "mana"

ON_HIT_APPLY_BEFORE_HIT = "before_hit"
ON_HIT_APPLY_AFTER_HIT = "after_hit"
ON_HIT_APPLY_NEXT_TURN = "next_turn"
RETURN_CODE_USED_ON_ATTACK_SPECIAL = 5
